development: 
  STRIPE_PUBLISHABLE_KEY: pk_test_IYfpVaTxWMSaEOP6N60R78aQ
  STRIPE_SECRET_KEY: sk_test_u4QITAafMYa7RMbWbWjnA7VA

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_IYfpVaTxWMSaEOP6N60R78aQ
  STRIPE_SECRET_KEY: sk_test_u4QITAafMYa7RMbWbWjnA7VA

production:
  STRIPE_PUBLISHABLE_KEY: pk_live_0jGV3O4ZN9mukRe1gyOLw5pC
  STRIPE_SECRET_KEY: sk_live_YMSrO8Pf8bIhGvJyFguaTFgt